kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.nodeName }}
  namespace: {{ .Values.metadata.namespace }}
  {{ if $.Values.ambassador.annotations }}
  annotations:
    getambassador.io/config: | 
    {{ $.Values.ambassador.annotations  | nindent 6 }}
  {{ end }}
  labels:
    run: {{ .Values.nodeName }}
    app.kubernetes.io/name: {{ .Values.nodeName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }} 
spec:
  type: {{ .Values.expressapp.serviceType }}
  selector:
    app: {{ .Values.nodeName }}
  ports:
  - port: {{ .Values.expressapp.nodePorts.port }}
    targetPort: {{ .Values.expressapp.nodePorts.targetPort }}
    protocol: TCP
    name: {{ .Values.expressapp.nodePorts.name }}

