apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mongodb-networkmap
  annotations:
    fluxcd.io/automated: "false"
  namespace: operator-a-ns
spec:
  replicaCount: 1
  replicas: 1
  releaseName: mongodb-networkmap
  chart:
    path: platforms/r3-corda/charts/mongodb
    git: git@github.com:5GZORRO/blockchain-automation-framework.git
    ref: operator-a
  values:
    nodeName: mongodb-networkmap
    metadata:
      namespace: operator-a-ns
    image:
      containerName: mongo:3.6.6
      imagePullSecret: regcred
      initContainerName: docker.pkg.github.com/5gzorro/blockchain-automation-framework/alpine-utils:1.0
    storage:
      memory: 512Mi
      name: longhornstorageclass
      mountPath: /data/db
      volname: hostvol
    vault:
      address: http://172.28.3.111
      role: vault-role
      authpath: cordanetworkmap
      secretprefix: networkmap/credentials/mongodb
      serviceaccountname: vault-auth
      certsecretprefix: networkmap/certs
    service:
      tcp:
          port: 27017
          targetPort: 27017
      type: NodePort
      annotations: {}
    deployment:
      annotations: {}
    pvc:
      annotations: {}
    mongodb:
      username: networkmap
    cluster:
      enabled: false