apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: operator-b-initial-registration
  annotations:
    fluxcd.io/automated: "false"
  namespace: operator-b-ns
spec:
  releaseName: operator-b-initial-registration
  chart:
    path: platforms/r3-corda/charts/node-initial-registration
    git: git@github.com:5GZORRO/blockchain-automation-framework.git
    ref: operator-b
  values:
    nodeName: operator-b
    replicas: 1
    metadata:
      namespace: operator-b-ns  
    image:
      containerName: index.docker.io/hyperledgerlabs/corda:4.4-linuxkit
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: 172.28.3.111
      networkmapCertAlias: 172.28.3.111
    nodeConf:
      p2p:
        url: operator-b.operator-b-ns
        port: 10002
      ambassadorAddress: operator-b.develop.local.com:15020
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=OperatorB,OU=Zurich,L=Zurich,C=CH #use peer-node level subject for legalName
      notaryServiceLegalName: O=HA Notary,OU=Notary,L=London,C=GB
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
       
      detectPublicIp: false
      database:
        transactionIsolationLevel: READ_COMMITTED
        exportHibernateJMXStatistics: false
      dbUrl: operator-bdb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://operator-bdb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: http://172.28.3.111:30040
      doormanURL: http://172.28.3.111:30030
      compatibilityZoneURL:
      jarVersion: 4.4
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: operator-boperations
          permissions: [ALL]

    volume:
      baseDir: /base/corda
    resources:
      limits: "512Mi"
      requests: "512Mi"
    
    service:
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
      rpcadmin:
        port: 10005

    vault:
      address: http://172.28.3.111
      role: vault-role
      authpath: cordaoperator-b
      serviceaccountname: vault-auth
      dbsecretprefix: operator-b/credentials/database
      rpcusersecretprefix: operator-b/credentials/rpcusers
      tokensecretprefix: operator-b/credentials/vaultroottoken
      keystoresecretprefix: operator-b/credentials/keystore
      certsecretprefix: operator-b/certs
        
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
