apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  annotations:
    getambassador.io/config: | 
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      name: {{ .Values.metadata.component_name }}_context
      hosts:
      - {{ .Values.metadata.component_name }}.{{ .Values.metadata.external_url_suffix }}
      secret: {{ .Values.metadata.component_name }}-ambassador-certs
      ---
      apiVersion: ambassador/v1
      kind: TCPMapping
      name: {{ .Values.metadata.component_name }}_p2p_mapping
      port: {{ .Values.metadata.p2p_ambassador }}
      host: {{ .Values.metadata.component_name }}.{{ .Values.metadata.external_url_suffix }}
      service: {{ .Values.metadata.component_name }}.{{ .Values.metadata.namespace }}:{{ .Values.metadata.port }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    run: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- include "labels.custom" . | nindent 2 }}
spec:
    type: {{ .Values.service.type }}
    selector:
      app: {{ .Values.nodeName }}
    ports:
    # for p2p communication among corda node
    - name: p2p
      protocol: TCP
      port: {{ .Values.service.p2p.port }}
      targetPort: {{ .Values.service.p2p.targetPort }}
      {{- if .Values.service.p2p.nodePort }}
      nodePort: {{ .Values.service.p2p.nodePort}}
      {{- end }}
    # for rpc communication between corda node and webserver
    - name: rpc
      protocol: TCP
      port: {{ .Values.service.rpc.port }}
      targetPort: {{ .Values.service.rpc.targetPort }}
      {{- if .Values.service.rpc.nodePort }}
      nodePort: {{ .Values.service.rpc.nodePort}}
      {{- end }}
    # for rpc admin communication 
    - name: rpcadmin
      protocol: TCP
      port: {{ .Values.service.rpcadmin.port }}
      targetPort: {{ .Values.service.rpcadmin.targetPort }}
      {{- if .Values.service.rpcadmin.nodePort }}
      nodePort: {{ .Values.service.rpcadmin.nodePort}}
      {{- end }}          