apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: operatora
  annotations:
    fluxcd.io/automated: "false"
  namespace: operatora-ns
spec:
  releaseName: operatora
  chart:
    path: platforms/r3-corda/charts/node
    git: git@github.com:5GZORRO/blockchain-automation-framework.git
    ref: operatora
  values:
    nodeName: operatora
    replicas: 1
    metadata:
      namespace: operatora-ns
    image:
      containerName: index.docker.io/hyperledgerlabs/corda:4.4-linuxkit
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: 172.28.3.111
      networkmapCertAlias: 172.28.3.111
    nodeConf:
      p2p:
        url: operatora.operatora-ns
        port: 10002
      ambassadorAddress: operatora.develop.local.com:15020
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: CN=OperatorA,OU=DLT,O=DLT,L=London,C=GB #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
       
      detectPublicIp: false
      database:
        transactionIsolationLevel: READ_COMMITTED
        exportHibernateJMXStatistics: false
      dbUrl: operatoradb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://operatoradb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: http://172.28.3.111:30040
      doormanURL: http://172.28.3.111:30030
      compatibilityZoneURL:
      jarVersion: 4.4
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: operatoraoperations
          permissions: [ALL]

    cordapps:
      getcordapps: false

    volume:
      baseDir: /base/corda
    resources:
      limits: "1Gi"
      requests: "1Gi" 
    pvc:
      name: operatora-pvc
      annotations: {}
      memory: 512Mi
      storageClassName: longhornstorageclass

    service:
      name: operatora
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
        targetPort: 10003 
      rpcadmin:
        port: 10005
        targetPort: 10005
         
    deployment:
      annotations: {}
    vault:
      address: http://172.28.3.111
      role: vault-role
      authpath: cordaoperatora
      serviceaccountname: vault-auth
      dbsecretprefix: operatora/credentials/database
      rpcusersecretprefix: operatora/credentials/rpcusers
      tokensecretprefix: operatora/credentials/vaultroottoken
      keystoresecretprefix: operatora/credentials/keystore
      certsecretprefix: operatora/certs
      networkmapsecretprefix: operatora/credentials/networkmappassword
      cordappsreposecretprefix: operatora/credentials/cordapps

          
    healthcheck:
      readinesscheckinterval: 20
      readinessthreshold: 20
    ambassador:
      component_name: operatora
      external_url_suffix: develop.local.com
      p2p_ambassador: 15020
